apiVersion: apps/v1
kind: Deployment
metadata:
  name: managerMessage
  labels:
    app: managerMessage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: managerMessage
  template:
    metadata:
      labels:
        app: managerMessage
    spec:
      containers:
        - name: managerMessage
          image: username/managerMessage:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5